pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/SRCEM-AIM-Class-A/A_55_Kartikey_django_app.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t kartikeyyy22/studentproject .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push your-dockerhub-username/studentproject'
                }
            }
        }
    }
}
